[package]
name = "rfc2047_decoder"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
charset = "0.1.2"
quoted_printable = "0.4.2"
